src/ProjectMann.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectMann.Core.Domain;
using ProjectMann.Infrastructure.Data;
using ProjectMann.Web.Managers;

namespace ProjectMann.Web.Controllers
{
    [Authorize("AdminAndDev")]
    public class ProjectController : Controller
    {
        private readonly ProjectMannDbContext _context;
        private readonly IAuthManager _auth;

        public ProjectController(ProjectMannDbContext context, IAuthManager auth)
        {
            _context = context;
            _auth = auth;
        }

        [Authorize("AdminAndDev")]
        // GET: Project
        public async Task<IActionResult> Index()
        {
            var projectMannDbContext = _context.Proyectos.Include(p => p.FkClienteNavigation).Include(p => p.FkEstadoNavigation).Include(p => p.FkUsuarioCreaNavigation).Include(p => p.FkUsuarioModificaNavigation);
            return View(await projectMannDbContext.ToListAsync());
        }

        [Authorize("AdminAndDev")]
        // GET: Project/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos
                .Include(p => p.FkClienteNavigation)
                .Include(p => p.FkEstadoNavigation)
                .Include(p => p.FkUsuarioCreaNavigation)
                .Include(p => p.FkUsuarioModificaNavigation)
                .FirstOrDefaultAsync(m => m.IdProyecto == id);
            if (proyecto == null)
            {
                return NotFound();
            }

            return View(proyecto);
        }

        [Authorize("Admin")]
        // GET: Project/Create
        public IActionResult Create()
        {
            ViewData["FkCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nombre");
            ViewData["FkEstado"] = new SelectList(_context.Estados, "IdEstado", "Nombre");
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "Apellido");
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "Apellido");
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize("Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProyecto,NombreProyecto,FkEstado,FkCliente,FechaCreacion,FechaModificacion,FkUsuarioModifica,FkUsuarioCrea")] Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                proyecto.FechaCreacion = DateTime.UtcNow.AddHours(-5);
                proyecto.FechaModificacion = DateTime.UtcNow.AddHours(-5);
                proyecto.FkUsuarioCrea = _auth.GetCurrentUserId(HttpContext);
                proyecto.FkUsuarioModifica = _auth.GetCurrentUserId(HttpContext);
                proyecto.FkEstado = 1;

                _context.Add(proyecto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nombre", proyecto.FkCliente);
            ViewData["FkEstado"] = new SelectList(_context.Estados, "IdEstado", "Nombre", proyecto.FkEstado);
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", proyecto.FkUsuarioCrea);
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", proyecto.FkUsuarioModifica);
            return View(proyecto);
        }

        // GET: Project/Edit/5
        [Authorize("Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos.FindAsync(id);
            if (proyecto == null)
            {
                return NotFound();
            }
            ViewData["FkCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nombre", proyecto.FkCliente);
            ViewData["FkEstado"] = new SelectList(_context.Estados, "IdEstado", "Nombre", proyecto.FkEstado);
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", proyecto.FkUsuarioCrea);
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", proyecto.FkUsuarioModifica);
            return View(proyecto);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize("Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProyecto,NombreProyecto,FkEstado,FkCliente,FechaCreacion,FechaModificacion,FkUsuarioModifica,FkUsuarioCrea")] Proyecto proyecto)
        {
            if (id != proyecto.IdProyecto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var proyectoActual = await _context.Proyectos
                        .Where(x => x.IdProyecto == id)
                        .Select(x => new { x.FechaCreacion, x.FkUsuarioCrea })
                        .FirstOrDefaultAsync();

                    if (proyectoActual == null)
                    {
                        return NotFound();
                    }

                    proyecto.FechaModificacion = DateTime.UtcNow.AddHours(-5);
                    proyecto.FkUsuarioModifica = _auth.GetCurrentUserId(HttpContext);
                    proyecto.FechaCreacion = proyectoActual.FechaCreacion;
                    proyecto.FkUsuarioCrea = proyectoActual.FkUsuarioCrea;
                    _context.Update(proyecto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProyectoExists(proyecto.IdProyecto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nombre", proyecto.FkCliente);
            ViewData["FkEstado"] = new SelectList(_context.Estados, "IdEstado", "Nombre", proyecto.FkEstado);
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", proyecto.FkUsuarioCrea);
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", proyecto.FkUsuarioModifica);
            return View(proyecto);
        }

        // GET: Project/Delete/5
        [Authorize("Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos
                .Include(p => p.FkClienteNavigation)
                .Include(p => p.FkEstadoNavigation)
                .Include(p => p.FkUsuarioCreaNavigation)
                .Include(p => p.FkUsuarioModificaNavigation)
                .FirstOrDefaultAsync(m => m.IdProyecto == id);
            if (proyecto == null)
            {
                return NotFound();
            }

            return View(proyecto);
        }

        // POST: Project/Delete/5
        [Authorize("Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proyecto = await _context.Proyectos.FindAsync(id);
            proyecto.FkEstado = 7;
            proyecto.FechaModificacion = DateTime.UtcNow.AddHours(-5);
            proyecto.FkUsuarioModifica = _auth.GetCurrentUserId(HttpContext);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProyectoExists(int id)
        {
            return _context.Proyectos.Any(e => e.IdProyecto == id);
        }
    }
}

src/ProjectMann.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectMann.Core.Domain;
using ProjectMann.Infrastructure.Data;
using ProjectMann.Web.Managers;

namespace ProjectMann.Web.Controllers
{
    [Authorize("AdminAndDev")]
    public class UserController : Controller
    {
        private readonly ProjectMannDbContext _context;
        private readonly IAuthManager _auth;

        public UserController(ProjectMannDbContext context, IAuthManager auth)
        {
            _context = context;
            _auth = auth;
        }

        [Authorize("AdminAndDev")]
        // GET: User
        public async Task<IActionResult> Index()
        {
            var projectMannDbContext = _context.Usuarios.Include(u => u.FkRolNavigation).Include(u => u.FkUsuarioCreaNavigation).Include(u => u.FkUsuarioModificaNavigation);
            return View(await projectMannDbContext.ToListAsync());
        }

        [Authorize("AdminAndDev")]
        // GET: User/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.FkRolNavigation)
                .Include(u => u.FkUsuarioCreaNavigation)
                .Include(u => u.FkUsuarioModificaNavigation)
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        [Authorize("Admin")]
        // GET: User/Create
        public IActionResult Create()
        {
            ViewData["FkRol"] = new SelectList(_context.Rols, "IdRol", "Nombre");
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario");
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario");
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize("Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUsuario,Nombre,Apellido,Clave,FkRol,NombreUsuario,Email,Estado,FechaCreacion,FechaModificacion,FkUsuarioModifica,FkUsuarioCrea")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.FechaCreacion = DateTime.UtcNow.AddHours(-5);
                usuario.FechaModificacion = DateTime.UtcNow.AddHours(-5);
                usuario.FkUsuarioCrea = _auth.GetCurrentUserId(HttpContext);
                usuario.FkUsuarioModifica = _auth.GetCurrentUserId(HttpContext);

                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkRol"] = new SelectList(_context.Rols, "IdRol", "Nombre", usuario.FkRol);
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", usuario.FkUsuarioCrea);
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", usuario.FkUsuarioModifica);
            return View(usuario);
        }

        // GET: User/Edit/5
        [Authorize("Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            ViewData["FkRol"] = new SelectList(_context.Rols, "IdRol", "Nombre", usuario.FkRol);
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", usuario.FkUsuarioCrea);
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", usuario.FkUsuarioModifica);
            return View(usuario);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuario,Nombre,Apellido,Clave,FkRol,NombreUsuario,Email,Estado,FechaCreacion,FechaModificacion,FkUsuarioModifica,FkUsuarioCrea")] Usuario usuario)
        {
            if (id != usuario.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var usuarioActual = await _context.Usuarios
                        .Where(x => x.IdUsuario == id)
                        .Select(x => new { x.FechaCreacion, x.FkUsuarioCrea })
                        .FirstOrDefaultAsync();

                    if (usuarioActual == null)
                    {
                        return NotFound();
                    }

                    usuario.FechaModificacion = DateTime.UtcNow.AddHours(-5);
                    usuario.FkUsuarioModifica = _auth.GetCurrentUserId(HttpContext);
                    usuario.FechaCreacion = usuarioActual.FechaCreacion;
                    usuario.FkUsuarioCrea = usuarioActual.FkUsuarioCrea;

                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkRol"] = new SelectList(_context.Rols, "IdRol", "Nombre", usuario.FkRol);
            ViewData["FkUsuarioCrea"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", usuario.FkUsuarioCrea);
            ViewData["FkUsuarioModifica"] = new SelectList(_context.Usuarios, "IdUsuario", "NombreUsuario", usuario.FkUsuarioModifica);
            return View(usuario);
        }

        // GET: User/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .Include(u => u.FkRolNavigation)
                .Include(u => u.FkUsuarioCreaNavigation)
                .Include(u => u.FkUsuarioModificaNavigation)
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: User/Delete/5
        [Authorize("Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            
            usuario.FechaModificacion = DateTime.UtcNow.AddHours(-5);
            usuario.FkUsuarioModifica = _auth.GetCurrentUserId(HttpContext);

            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.IdUsuario == id);
        }
    }
}

src/ProjectMann.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMann</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectMann</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if (User.IsInRole("1") || User.IsInRole("2"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="WorkItem" asp-action="Index">
                                        Items de Trabajo
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">
                                        Proyectos
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">
                                        Inventario
                                    </a>
                                </li>
                            }

                            @if (User.IsInRole("1"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                        asp-action="Index">Usuarios</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CustomerService" asp-action="Index">
                                    Servicio al cliente
                                </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">
                                    Cerrar Sesión
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="javascript:void(0)">
                                    @User.Identity.Name
                                </a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - ProjectMann
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>